### ISSUE TITLE
add max length for help command

### ISSUE THREAD

**Issue by JyhuKo** [xMistt/rebootpy#2]
There is now a max length of 256 so the default help command can't work if you have a lot of commands

**Comment by xMistt** [comment]
Thanks for letting me know, I'll rework the command to work with the new message system.

**Comment by xMistt** [comment]
Fixed in https://github.com/xMistt/rebootpy/commit/9714b2dd4cd48dbab92ef6d7b70097ab0767b112, I tested & had no issues, but if you have any, please let me know here by reopening this issue. These changes will be in the next pypi release which will either be today or tomorrow but if you need it before then, you can download directly from GitHub.
